### ISSUE TITLE
[arenamaster] concurrency issue/crash

### ISSUE THREAD

**Issue by xtuc** [ByteArena/backends#203]
```sh
{"time":"2017-10-16T09:55:11Z","lvl":"debug","service":"healthcheck","message":"Arena 00:f0:09:fe:f4:76 reported health OK","context":{"hostname":"sd-58059"}}
{"time":"2017-10-16T09:55:15Z","lvl":"debug","service":"vm","message":"VM (4) booted","context":{"hostname":"sd-58059"}}
panic: sync: negative WaitGroup counter

goroutine 65 [running]:
sync.(*WaitGroup).Add(0xc4201722d8, 0xffffffffffffffff)
        /usr/local/go/src/sync/waitgroup.go:75 +0x1c9
sync.(*WaitGroup).Done(0xc4201722d8)
        /usr/local/go/src/sync/waitgroup.go:100 +0x34
github.com/bytearena/bytearena/vendor/github.com/bytearena/schnapps/scheduler.(*Pool).consumeEvents(0xc4201722a0)
        /go/src/github.com/bytearena/bytearena/vendor/github.com/bytearena/schnapps/scheduler/scheduler.go:231 +0x293
created by github.com/bytearena/bytearena/vendor/github.com/bytearena/schnapps/scheduler.NewFixedVMPool
        /go/src/github.com/bytearena/bytearena/vendor/github.com/bytearena/schnapps/scheduler/scheduler.go:60 +0x2d1
```

**Comment by xtuc** [comment]
Fixed upstream
