### ISSUE TITLE
Fresh install of `ba`v0.0.5 crashes upon `ba train -agent demoagent`

### ISSUE THREAD

**Issue by netgusto** [ByteArena/backends#236]
```
jerome@Jeromes-MBP ~/C/o/bytearena-docs> ba train -agent demoagent
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x119496e]

goroutine 1 [running]:
github.com/bytearena/bytearena/vendor/github.com/xtuc/better-errors/printer/tree.printChain(0xc42000ad40, 0x2, 0x1f, 0xc42000ae20)
        /home/sven/go/src/github.com/bytearena/bytearena/vendor/github.com/xtuc/better-errors/printer/tree/tree.go:20 +0x3e
github.com/bytearena/bytearena/vendor/github.com/xtuc/better-errors/printer/tree.printChain(0xc42000ad20, 0x2, 0x1a, 0xc42000ade0)
        /home/sven/go/src/github.com/bytearena/bytearena/vendor/github.com/xtuc/better-errors/printer/tree/tree.go:29 +0x383
github.com/bytearena/bytearena/vendor/github.com/xtuc/better-errors/printer/tree.printChain(0xc4204c34f0, 0x1, 0xc4204e2240, 0xc4204e2240)
        /home/sven/go/src/github.com/bytearena/bytearena/vendor/github.com/xtuc/better-errors/printer/tree/tree.go:29 +0x383
github.com/bytearena/bytearena/vendor/github.com/xtuc/better-errors/printer/tree.PrintChain(0xc4204c34f0, 0xc420016f60, 0xc4204c34e0)
        /home/sven/go/src/github.com/bytearena/bytearena/vendor/github.com/xtuc/better-errors/printer/tree/tree.go:14 +0x34
github.com/bytearena/bytearena/common/utils.FailWith(0x19bb8c0, 0xc42000ad20)
        /home/sven/go/src/github.com/bytearena/bytearena/common/utils/failWith.go:23 +0x28b
github.com/bytearena/bytearena/ba/action/train.TrainAction(0xa, 0xc4200127a0, 0xd, 0x1f90, 0x0, 0x0, 0x0, 0xc420012570, 0x1, 0x1, ...)
        /home/sven/go/src/github.com/bytearena/bytearena/ba/action/train/main.go:72 +0x11d7
main.makeapp.func3(0xc420096840, 0x0, 0xc420096840)
        /home/sven/go/src/github.com/bytearena/bytearena/cmd/ba/main.go:110 +0x34b
github.com/bytearena/bytearena/vendor/github.com/urfave/cli.HandleAction(0x15c5fc0, 0x16bf670, 0xc420096840, 0xc42006c100, 0x0)
        /home/sven/go/src/github.com/bytearena/bytearena/vendor/github.com/urfave/cli/app.go:490 +0xd4
github.com/bytearena/bytearena/vendor/github.com/urfave/cli.Command.Run(0x169b1e2, 0x5, 0x0, 0x0, 0xc420012380, 0x1, 0x1, 0x16a64f7, 0x10, 0x0, ...)
        /home/sven/go/src/github.com/bytearena/bytearena/vendor/github.com/urfave/cli/command.go:210 +0xb6e
github.com/bytearena/bytearena/vendor/github.com/urfave/cli.(*App).Run(0xc420518000, 0xc420072040, 0x4, 0x4, 0x0, 0x0)
        /home/sven/go/src/github.com/bytearena/bytearena/vendor/github.com/urfave/cli/app.go:255 +0x76f
main.main()
        /home/sven/go/src/github.com/bytearena/bytearena/cmd/ba/main.go:25 +0xc4
```

**Comment by netgusto** [comment]
It's because `hexagon.zip` freshly downloaded from dl.bytearena.com is corrupted.

```
jerome@Jeromes-MBP ~/C/g/s/g/b/b/c/ba> unzip hexagon.zip
Archive:  hexagon.zip
  inflating: index.html
file #2:  bad zipfile offset (local header sig):  988
file #3:  bad zipfile offset (local header sig):  1050
file #4:  bad zipfile offset (local header sig):  1571
file #5:  bad zipfile offset (local header sig):  1637
file #6:  bad zipfile offset (local header sig):  2008
file #7:  bad zipfile offset (local header sig):  2073
file #8:  bad zipfile offset (local header sig):  3639
file #9:  bad zipfile offset (local header sig):  183422
file #10:  bad zipfile offset (local header sig):  184264
file #11:  bad zipfile offset (local header sig):  184330
   creating: map/json/
  inflating: map/json/config.json
  inflating: map/json/model.json.gz
  inflating: map/json/scene.json
  inflating: map/json/manifest.json
   creating: lib/
  inflating: lib/bytearenaviz.min.js
  inflating: map.json
```

**Comment by xtuc** [comment]
Could you try to `ba map update`? It should delete the corrupted file.

**Comment by netgusto** [comment]
Resolved.
