### ISSUE TITLE
Error on Initialization when using multiple agents

### ISSUE THREAD

**Issue by edi9999** [ByteArena/backends#25]
This situation happens only with multiple agents : 

with 1 agent it never happens
with 2 agents, it happens sometimes
with 3 or more agents, it happen almost always

I get the following output and my server crashes :

```
go build && HOST=$(localip) PORT=8888 TPS=4 AGENTS=3 AGENTIMP=seeker ./arena
2017/04/05 09:24:11 listening on 192.168.0.35:8888
2017/04/05 09:24:11 Viz Listening on http://192.168.0.35:8889
2017/04/05 09:24:11
2017/04/05 09:24:11 Spawning agent 309255b1-3507-4d6a-b133-08d32c034433 in its own container
2017/04/05 09:24:11
2017/04/05 09:24:11
2017/04/05 09:24:11 Spawning agent 5d19f9db-0e09-44db-b3a9-837c3bc8394c in its own container
2017/04/05 09:24:11
2017/04/05 09:24:11
2017/04/05 09:24:11 Spawning agent 182db6fb-d722-482d-9b26-d2a586f7ff4e in its own container
2017/04/05 09:24:11
2017/04/05 09:24:12 Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:270: sending config to init process caused \"write parent: broken pipe\""
panic: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:270: sending config to init process caused \"write parent: broken pipe\""


goroutine 21 [running]:
panic(0x780c00, 0xc4203fc280)
        /home/edgar/go/src/runtime/panic.go:500 +0x1a1
log.Panicln(0xc42005df78, 0x1, 0x1)
        /home/edgar/go/src/log/log.go:334 +0xc9
github.com/netgusto/bytearena/server.(*Swarm).Spawnagent(0xc42010c360)
        /home/edgar/gocode/src/github.com/netgusto/bytearena/server/swarm.go:70 +0x250
created by main.main
        /home/edgar/gocode/src/github.com/netgusto/bytearena/cmd/arena/main.go:296 +0x287
```

```
docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:38:57 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:38:57 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
go version
go version go1.7.1 linux/amd64
```

**Comment by xtuc** [comment]
I have the same versions of Docker. If you are launching docker engine directly (`dockerd`), could you include the output?

**Comment by edi9999** [comment]
Here is my `sudo journalctl -u docker`

```
Apr 05 09:24:12 fr-fadpc15.edgar dockerd[5577]: time="2017-04-05T09:24:12.493364439+02:00" level=error msg="containerd: start container" error="oci runtime error: container_linux.go:247: starting container prnocess caused \"process_linux.go:270: sending config to init process caused \\\"write parent: broken pipe\\\"\"\n" id=fb38a95ef6087012dfe0eab441e8aa1b48ec43901c0a74774f5309b190ce0e7f
Apr 05 09:24:12 fr-fadpc15.edgar dockerd[5577]: time="2017-04-05T09:24:12.496378041+02:00" level=error msg="Create container failed with error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:270: sending config to init process caused \\\"write parent: broken pipe\\\"\"\n"
Apr 05 09:24:12 fr-fadpc15.edgar dockerd[5577]: time="2017-04-05T09:24:12.543665017+02:00" level=error msg="containerd: start container" error="oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:286: decoding sync type from init pipe caused \\\"read parent: connection reset by peer\\\"\"\n" id=ca5c29f1658f230b900ed6adc6254738a1197c962ee36b491dcd4c1c4d755708
Apr 05 09:24:12 fr-fadpc15.edgar dockerd[5577]: time="2017-04-05T09:24:12.544696930+02:00" level=error msg="Create container failed with error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:286: decoding sync type from init pipe caused \\\"read parent: connection reset by peer\\\"\"\n"
Apr 05 09:24:12 fr-fadpc15.edgar dockerd[5577]: time="2017-04-05T09:24:12.546065239+02:00" level=error msg="containerd: start container" error="oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"error running hook: exit status 2, stdout: , stderr: runtime/cgo: pthread_create failed: Resource temporarily unavailable\\\\nSIGABRT: abort\\\\nPC=0x7f7395d0d765 m=0\\\\n\\\\ngoroutine 0 [idle]:\\\\n\\\\ngoroutine 1 [running]:\\\\nruntime.systemstack_switch()\\\\n\\\\t/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420024768 sp=0xc420024760\\\\nruntime.main()\\\\n\\\\t/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200247c0 sp=0xc420024768\\\\nruntime.goexit()\\\\n\\\\t/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200247c8 sp=0xc4200247c0\\\\n\\\\ngoroutine 17 [syscall, locked to thread]:\\\\nruntime.goexit()\\\\n\\\\t/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1\\\\n\\\\nrax    0x0\\\\nrbx    0x7f73960966e0\\\\nrcx    0x7f7395d0d765\\\\nrdx    0x6\\\\nrdi    0x3c2b\\\\nrsi    0x3c2b\\\\nrbp    0x1a5f60d\\\\nrsp    0x7ffe0f527458\\\\nr8     0x7f7396097750\\\\nr9     0x7f7396a97880\\\\nr10    0x8\\\\nr11    0x206\\\\nr12    0x2d69080\\\\nr13    0xf3\\\\nr14    0x30\\\\nr15    0x3\\\\nrip    0x7f7395d0d765\\\\nrflags 0x206\\\\ncs     0x33\\\\nfs     0x0\\\\ngs     0x0\\\\n\\\"\"\n" id=f6fadb69e2586301fd1a4943210876495cccfdb49726171a3de7c73a74e48760
Apr 05 09:24:12 fr-fadpc15.edgar dockerd[5577]: time="2017-04-05T09:24:12.547643579+02:00" level=error msg="Create container failed with error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"error running hook: exit status 2, stdout: , stderr: runtime/cgo: pthread_create failed: Resource temporarily unavailable\\\\nSIGABRT: abort\\\\nPC=0x7f7395d0d765 m=0\\\\n\\\\ngoroutine 0 [idle]:\\\\n\\\\ngoroutine 1 [running]:\\\\nruntime.systemstack_switch()\\\\n\\\\t/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420024768 sp=0xc420024760\\\\nruntime.main()\\\\n\\\\t/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200247c0 sp=0xc420024768\\\\nruntime.goexit()\\\\n\\\\t/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200247c8 sp=0xc4200247c0\\\\n\\\\ngoroutine 17 [syscall, locked to thread]:\\\\nruntime.goexit()\\\\n\\\\t/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1\\\\n\\\\nrax    0x0\\\\nrbx    0x7f73960966e0\\\\nrcx    0x7f7395d0d765\\\\nrdx    0x6\\\\nrdi    0x3c2b\\\\nrsi    0x3c2b\\\\nrbp    0x1a5f60d\\\\nrsp    0x7ffe0f527458\\\\nr8     0x7f7396097750\\\\nr9     0x7f7396a97880\\\\nr10    0x8\\\\nr11    0x206\\\\nr12    0x2d69080\\\\nr13    0xf3\\\\nr14    0x30\\\\nr15    0x3\\\\nrip    0x7f7395d0d765\\\\nrflags 0x206\\\\ncs     0x33\\\\nfs     0x0\\\\ngs     0x0\\\\n\\\"\"\n"
Apr 05 09:24:12 fr-fadpc15.edgar dockerd[5577]: time="2017-04-05T09:24:12.736638397+02:00" level=error msg="Handler for POST /v1.29/containers/fb38a95ef6087012dfe0eab441e8aa1b48ec43901c0a74774f5309b190ce0e7f/start returned error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:270: sending config to init process caused \\\"write parent: broken pipe\\\"\"\n"
Apr 05 09:24:12 fr-fadpc15.edgar dockerd[5577]: time="2017-04-05T09:24:12.833536094+02:00" level=error msg="Handler for POST /v1.29/containers/ca5c29f1658f230b900ed6adc6254738a1197c962ee36b491dcd4c1c4d755708/start returned error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:286: decoding sync type from init pipe caused \\\"read parent: connection reset by peer\\\"\"\n"
Apr 05 09:24:12 fr-fadpc15.edgar dockerd[5577]: time="2017-04-05T09:24:12.892881473+02:00" level=error msg="Handler for POST /v1.29/containers/f6fadb69e2586301fd1a4943210876495cccfdb49726171a3de7c73a74e48760/start returned error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"error running hook: exit status 2, stdout: , stderr: runtime/cgo: pthread_create failed: Resource temporarily unavailable\\\\nSIGABRT: abort\\\\nPC=0x7f7395d0d765 m=0\\\\n\\\\ngoroutine 0 [idle]:\\\\n\\\\ngoroutine 1 [running]:\\\\nruntime.systemstack_switch()\\\\n\\\\t/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420024768 sp=0xc420024760\\\\nruntime.main()\\\\n\\\\t/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200247c0 sp=0xc420024768\\\\nruntime.goexit()\\\\n\\\\t/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200247c8 sp=0xc4200247c0\\\\n\\\\ngoroutine17 [syscall, locked to thread]:\\\\nruntime.goexit()\\\\n\\\\t/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1\\\\n\\\\nrax    0x0\\\\nrbx    0x7f73960966e0\\\\nrcx    0x7f7395d0d765\\\\nrdx  0x6\\\\nrdi    0x3c2b\\\\nrsi    0x3c2b\\\\nrbp    0x1a5f60d\\\\nrsp    0x7ffe0f527458\\\\nr8     0x7f7396097750\\\\nr9     0x7f7396a97880\\\\nr10    0x8\\\\nr11    0x206\\\\nr12    0x2d69080\\\\nr13    0xf3\\\\nr14    0x30\\\\nr15    0x3\\\\nrip    0x7f7395d0d765\\\\nrflags 0x206\\\\ncs     0x33\\\\nfs     0x0\\\\ngs     0x0\\\\n\\\"\"\n"
```

**Comment by netgusto** [comment]
I believe it's a race condition on this line :
https://github.com/netgusto/bytearena/blob/master/server/server.go#L60

Because of the fact that we spawn containers concurrently here:
https://github.com/netgusto/bytearena/blob/master/cmd/arena/main.go#L320

We do it concurrently to speed up container spawning (otherwise, time to wait is long if many containers are spawned)

**Comment by netgusto** [comment]
I pushed a fix on branch fix-issue-25; I believe it resolves this issue as I successfully spawned 300 agents at a time on my nixbox (couldn't do it before). @edi9999 Could you please confirm ?

**Comment by edi9999** [comment]
Yes it is working fine !

**Comment by netgusto** [comment]
I'll merge this then.
